# Generated by Django 4.0.1 on 2022-01-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_citymodel_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='other_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Other Name'),
        ),
    ]
